### PR TITLE
Fix delete file error

### PR DESCRIPTION
**Pull request by ssuuyyuu**
The issue is that when calling the post method, the body part is missing. The fix is to pass the keys in as path and then later to be used as the body for the post method.

### CODE REVIEW

**Comment by ssuuyyuu** [comment]
@emilienh @paiv Could you please take a look? It's fixing the issue for us. Thanks!

**Comment by mahdi-canva** [comment]
Hey @vsolovei-smartling 
The ruby SDK seems to be abandoned with the last update made in 2016. Could you please look into this or tag the right people to get this prioritized/merged? Thanks.

**Comment by ssuuyyuu** [comment]
@vsolovei-smartling I just bumped the version as well.

**Comment by dimitrystd** [comment]
Hi @mahdi-canva @ssuuyyuu,
I merged your PR, but I need to let you know that Smartling will no longer support this SDK because of its low popularity and our limited resources. I suggest you use a fork for your projects. Thanks for understanding.

**Pull request merged**
